camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
#      first-name: demo

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

server:
  port: 8080